<?php

$products = [
    [
        'id' => 1,
        'type' => 'cibo',
        'name' => 'Croccantini Premium',
        'price' => 19.99,
        'availability' => true,
        'category' => 'cane',
        'description' => 'Croccantini premium per cani di taglia media',
        'quantity_available' => 50,
        'ingredients' => ['pollo', 'riso', 'orzo'],
        'fats' => 12,
        'proteins' => 24,
        'carbohydrates' => 40,
    ],
    [
        'id' => 2,
        'type' => 'gioco',
        'name' => 'Gioco da Masticare Resistente',
        'price' => 12.49,
        'availability' => true,
        'category' => 'cane',
        'description' => 'Gioco resistente per masticatori forti, adatto a cani di tutte le taglie',
        'quantity_available' => 30,
        'material' => 'gomma resistente',
        'size' => 'l',
    ],
    [
        'id' => 3,
        'type' => 'cuccia',
        'name' => 'Cuccia Morbida Comfort',
        'price' => 39.99,
        'availability' => true,
        'category' => 'cane',
        'description' => 'Cuccia morbida e confortevole per il riposo del tuo cane',
        'quantity_available' => 20,
        'dimensions' => ['length' => 80, 'width' => 60, 'height' => 20],
    ],
    [
        'id' => 4,
        'type' => 'cibo',
        'name' => 'Scatolette Gourmet',
        'price' => 2.99,
        'availability' => true,
        'category' => 'gatto',
        'description' => 'Scatolette gourmet per gatti, varietà di sapori',
        'quantity_available' => 100,
        'ingredients' => ['tonno', 'salmone', 'riso'],
        'fats' => 8,
        'proteins' => 18,
        'carbohydrates' => 35,
    ],
    [
        'id' => 5,
        'type' => 'gioco',
        'name' => 'Palla Rimbalzante con Campana',
        'price' => 6.99,
        'availability' => true,
        'category' => 'gatto',
        'description' => 'Palla rimbalzante con campana per intrattenere il tuo gatto',
        'quantity_available' => 40,
        'material' => 'plastica resistente',
        'size' => 'm',
    ],
    [
        'id' => 6,
        'type' => 'cuccia',
        'name' => 'Casetta Cozy per Gatti',
        'price' => 29.99,
        'availability' => true,
        'category' => 'gatto',
        'description' => 'Casetta morbida e confortevole per il riposo del tuo gatto',
        'quantity_available' => 15,
        'dimensions' => ['length' => 50, 'width' => 40, 'height' => 30],
    ],
    [
        'id' => 7,
        'type' => 'cibo',
        'name' => 'Snack Dentali per Cani',
        'price' => 9.99,
        'availability' => true,
        'category' => 'cane',
        'description' => 'Snack dentali per cani, favoriscono l\'igiene orale',
        'quantity_available' => 80,
        'ingredients' => ['manzo', 'riso', 'pere'],
        'fats' => 6,
        'proteins' => 18,
        'carbohydrates' => 30,
    ],
    [
        'id' => 8,
        'type' => 'gioco',
        'name' => 'Pallina Squeaky per Gatti',
        'price' => 5.49,
        'availability' => true,
        'category' => 'gatto',
        'description' => 'Pallina con suono squeaky per divertire il tuo gatto',
        'quantity_available' => 25,
        'material' => 'peluche',
        'size' => 's',
    ],
    [
        'id' => 9,
        'type' => 'cuccia',
        'name' => 'Letto Ortopedico per Cani',
        'price' => 59.99,
        'availability' => true,
        'category' => 'cane',
        'description' => 'Letto ortopedico per cani anziani o con problemi articolari',
        'quantity_available' => 10,
        'dimensions' => ['length' => 100, 'width' => 70, 'height' => 15],
    ],
    [
        'id' => 10,
        'type' => 'cibo',
        'name' => 'Paté Gourmet per Gatti',
        'price' => 3.99,
        'availability' => true,
        'category' => 'gatto',
        'description' => 'Paté gourmet per gatti, varietà di gusti prelibati',
        'quantity_available' => 60,
        'ingredients' => ['anatra', 'tonno', 'carote'],
        'fats' => 10,
        'proteins' => 20,
        'carbohydrates' => 25,
    ],
    [
        'id' => 11,
        'type' => 'gioco',
        'name' => 'Tunnel Pieghevole per Gatti',
        'price' => 15.99,
        'availability' => true,
        'category' => 'gatto',
        'description' => 'Tunnel pieghevole per gatti, ideale per il gioco e nascondigli',
        'quantity_available' => 35,
        'material' => 'nylon',
        'size' => 'xl',
    ],
    [
        'id' => 12,
        'type' => 'cuccia',
        'name' => 'Cuccia Riscaldata per Cani',
        'price' => 79.99,
        'availability' => true,
        'category' => 'cane',
        'description' => 'Cuccia con riscaldamento integrato per cani che amano il calore',
        'quantity_available' => 5,
        'dimensions' => ['length' => 120, 'width' => 90, 'height' => 25],
    ],
];